// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSB1WjCXS_TkYHBCbFWjqee1n2VhNaiw4',
    appId: '1:142968154058:web:4589db0255b9181e389133',
    messagingSenderId: '142968154058',
    projectId: 'tugasppbcsfaiz',
    authDomain: 'tugasppbcsfaiz.firebaseapp.com',
    storageBucket: 'tugasppbcsfaiz.firebasestorage.app',
    measurementId: 'G-FDVS07RZ3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG9NtRLh4k8yp7BhRFdA-yPeWlTROeT-c',
    appId: '1:142968154058:android:b2e8e6ed352a793c389133',
    messagingSenderId: '142968154058',
    projectId: 'tugasppbcsfaiz',
    storageBucket: 'tugasppbcsfaiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdPS0P0j89qT2QjUKWdh7QMWX4sM0I_7s',
    appId: '1:142968154058:ios:e6e8daf8e526e6d3389133',
    messagingSenderId: '142968154058',
    projectId: 'tugasppbcsfaiz',
    storageBucket: 'tugasppbcsfaiz.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdPS0P0j89qT2QjUKWdh7QMWX4sM0I_7s',
    appId: '1:142968154058:ios:e6e8daf8e526e6d3389133',
    messagingSenderId: '142968154058',
    projectId: 'tugasppbcsfaiz',
    storageBucket: 'tugasppbcsfaiz.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSB1WjCXS_TkYHBCbFWjqee1n2VhNaiw4',
    appId: '1:142968154058:web:c1b7ebac479500de389133',
    messagingSenderId: '142968154058',
    projectId: 'tugasppbcsfaiz',
    authDomain: 'tugasppbcsfaiz.firebaseapp.com',
    storageBucket: 'tugasppbcsfaiz.firebasestorage.app',
    measurementId: 'G-375CT2QYG4',
  );
}
